version: '3'

services:
  mongo:
    container_name: indocor-backs-mongo-1
    image: mongo:latest
    restart: on-failure
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:27017
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./docker/volumes/:/data/db
    env_file:
      - .env

volumes:
  mongo-data:
